spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_booking?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 5
          max-interval: 5s
          multiplier: 2

server:
  port: 8085
  servlet:
    context-path: /theatre-master-api
logging:
  file:
    name: D:/Development/WS/log/local/theatre-master-api/theatre-master-api.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.example.theatre.master: INFO
    org.springframework.web: TRACE

message:
  messageConfiguration:
    host: localhost
    port: 20004
    username: guest
    password: guest
    virtualHost: snk-rmq
  theatreDetailsExchangeConfiguration:
    exchange: movieScheduleExchange
    routingKey: movie.theatre.details
    queue: theatreDetailsQueue